site_name: QuaSi Software

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Explicitly set the version of Python and its requirements
python:
  version: 2 # for unicode
  setup_py_install: true
  install:
    - requirements: docs\requirements.txt

# set theme
theme: readthedocs

# activate markdown math for latex 
markdown_extensions:
  - mdx_math
  - footnotes 
  - attr_list

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

# navigation
nav:
  - Home:
      - 'QuaSi - Overview': 'index.md'
  - 'Simulation engine ReSiE':
      - 'Installation and usage': 'resie_installation.md'
      - 'Input file format': 'resie_input_file_format.md'
      - 'Simulation model':
          - 'Fundamentals': 'resie_fundamentals.md'
          - 'Energy systems': 'resie_energy_systems.md'
          - 'Types of energy system components': 'resie_types_components.md'
          - 'Operation and control': 'resie_operation_control.md'
      - 'Technical description': 
          - 'resie_description_components.md'
          - 'resie_transient_effects.md'
  - 'Contributions':
      - 'How to help': 'contributions.md'
      - 'Working on the documentation': 'changing_documentation.md'
      - 'Workflow for code contributions': 'workflow_code_contributions.md'
  - About:
      - 'License': 'license.md'