site_name: Dokumentation Quasi II

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Explicitly set the version of Python and its requirements
python:
  version: 2 # for unicode
  setup_py_install: true
  install:
    - requirements: docs\requirements.txt

# set theme
theme: readthedocs

# activate markdown math for latex 
markdown_extensions:
  - mdx_math
  - footnotes 
  
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']