site_name: Dokumentation Quasi II

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Explicitly set the version of Python and its requirements
python:
  version: 2 # for unicode
  setup_py_install: true
  install:
    - requirements: docs\requirements.txt

# set theme
theme: readthedocs

# activate markdown math for latex 
markdown_extensions:
  - mdx_math
  - footnotes 

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

# navigation
nav:
  - Home:
    - 'QuaSi - Overview': 'index.md'
  - 'Technical description': 
    - 'quasi_description_energy_systems.md'
    - 'quasi_transient_effects.md'
  - 'Simulation engine Resie':
    - 'Installation and usage': 'resie_installation.md'
    - 'Input file format': 'resie_input_file_format.md'
    - 'Simulation model':
      - 'Fundamentals': 'resie_fundamentals.md'
      - 'Energy network topology': 'resie_ennet_topology.md'
      - 'Types of energy systems': 'resie_types_energy_systems.md'
      - 'Operation and control': 'resie_operation_control.md'
  - 'Contributions':
    - 'How to help': 'contributions.md'
    - 'Working on the documentation': 'changing_documentation.md'
  - About:
    - 'License': 'license.md'